"""
This type stub file was generated by pyright.
"""

from .color_pair import ColorPair
from .spaces import Ansi256, Color, HCL, Hex, RGB, WebColor

"""Facilities for working with colors."""
__version__ = ...
__all__ = ["Ansi256", "Color", "ColorPair", "HCL", "Hex", "RGB", "WebColor"]
