"""
This type stub file was generated by pyright.
"""

"""
Colors by name.

This are the
["extended colors"](https://en.wikipedia.org/wiki/Web_colors#Extended_colors) from the
[CSS Color Module Level 3](https://www.w3.org/TR/css-color-3/#svg-color), which is the
result of merging specifications from HTML 4.01, CSS 2.0, SVG 1.0 and CSS3 User
Interfaces (CSS3 UI).
"""
colors = ...
