"""Test that files are encoded correctly."""

from pathlib import Path
import pytest

from textual_paint.ansi_art_document import AnsiArtDocument

ROUND_TRIP_EXCLUSIONS = [
    # These files are generated by a script, not the Textual Paint app, so they naturally change.
    "4x4_font_template.ans",
    "gradient_test.ans",
    # This one was free-handed with Inkscape, so naturally changes a lot.
    "pathological_character_grid.svg",
    # The `0x0.ans` file saves as 1x1, due to the minimum size.
    "0x0.ans",
    # This is a color palette file, meant to be loaded with Get Colors, not Open.
    "pipe_strip_palette.gpl",
    # THIS ONE MAYBE SHOULD IDEALLY WORK? But I need a better way of viewing a diff...
    "cp437_as_utf8.txt",
]
SAMPLES_DIR = Path(__file__).parent.parent / "samples"
SAMPLES = [f for f in SAMPLES_DIR.iterdir() if f.is_file() and "~" not in f.name]
ROUND_TRIP_SAMPLES = [f for f in SAMPLES if f.name not in ROUND_TRIP_EXCLUSIONS]

@pytest.mark.parametrize("file_path", ROUND_TRIP_SAMPLES)
def test_round_trip(file_path: Path) -> None:
    """Test that files are re-encoded identically when opened and saved."""
    with open(file_path, "rb") as f:
        file_content = f.read()
        image = AnsiArtDocument.decode_based_on_file_extension(file_content, str(file_path))
        assert image.encode_based_on_file_extension(str(file_path)) == file_content
