"""
This type stub file was generated by pyright.
"""

from .ansi import Ansi
from .attribute import SetAttribute
from .clear import SetClear
from .color import SetColor
from .cursor import SetCursor
from .escape import Escape
from .unsupported import Unsupported

"""A lightweight parser for ANSI escape sequences."""
__version__ = ...
__all__ = ["Ansi", "Escape", "SetAttribute", "SetClear", "SetColor", "SetCursor", "Unsupported"]
