"""
This type stub file was generated by pyright.
"""

from typing import Text

"""Private miscellaneous utilities."""
class _CustomText(Text):
    """A custom string type for subclassing."""
    def __repr__(self) -> Text:
        """Return a string representation of the object."""
        ...
    


