"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from enum import Enum
from .instruction import Instruction

"""Clear screen regions."""
class Clear(Enum):
    """Screen regions to clear."""
    SCREEN_AFTER = ...
    SCREEN_BEFORE = ...
    SCREEN = ...
    LINE_AFTER = ...
    LINE_BEFORE = ...
    LINE = ...


@dataclass
class SetClear(Instruction[Clear]):
    """Instruction to clear a screen region."""
    region: Clear
    ...


