"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from enum import Enum
from typing import Optional
from ochre import Color
from .instruction import Instruction

"""ANSI foreground and background colors."""
class ColorRole(Enum):
    """An ANSI color kinds: foreground or background."""
    FOREGROUND = ...
    BACKGROUND = ...


@dataclass
class SetColor(Instruction[Color]):
    """An ANSI instruction to set a foreground or background color."""
    role: ColorRole
    color: Optional[Color] = ...


