"""
This type stub file was generated by pyright.
"""

from typing import Generic, TypeVar

"""Generic ANSI instructions."""
T = TypeVar("T")
class Instruction(Generic[T]):
    """An ANSI instruction."""
    ...


