"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from .instruction import Instruction
from .token import Token

"""An instruction that we don't support."""
@dataclass
class Unsupported(Instruction[Token]):
    """An instruction that we don't support."""
    token: Token
    ...


